language: cpp
os: osx
branches:
  only:
  - master
before_install:
- brew update
- brew install qt5
script:
- "/usr/local/opt/qt/bin/qmake QWeave.pro"
- make
- "/usr/local/opt/qt/bin/macdeployqt QWeave.app -dmg"
deploy:
  provider: releases
  api_key:
    secure: Ay2Jzxa5ummLKGB50xdMUVQHHidZptMTw79RcRSHgSDYIqEHLNMptjacXaBPfebTFq6R41f1D77wv6Ky2Sw2mmROpYN7YTUizLSfjxxn4P7PAueX8WCOm/HXapdjenVxzkOeVdApXFCrljfsZj04JN/PVvGsWdc9GSUzpkrON3IY/yR/OH8WEMbzOFIUKpIDjRfWKVtT1YPTY5h0718PY7QInnV6lJRSJDuGa2E1WZ1/NSFFUwM/Oiq1hoq17IhnlmW8Dmk3rCWUR6iIwMXoPQll6/vwAeMa1dw0Zg9yXp5Dj6bDcX+qrpC9Nj9LMf0/qtCo5tQSkTd74vWpbBFRsBxYh9n/ED6D6qXqqU0JoY6bEvFhCC/8jQb5upJnoC2D7iLWGM4tJQUHisamD2T9++fE68/x6gV4JgJ2H6RqeUJHJDwq+sjknYrjxGMES/p9Mo3obs+wE+SbjWat1rkkM7+Ow6mbUXKKD3b7HMsz01w9ExP+7uE71ayu37UsLbrCa7XfHu2QtKdHL8zMHogW/NjwaONHku2ruCW8Cc8/0FjFDWq0XpriK7ySuYuhgWbP38WKzKyQA531Yh/kaTJAplPWUOf3NPue3fEStBtGrrHutunHWdZfvfjZ+Z3kNKC6+Sw4ne+JgScIM+Z7PKhLKpiU/cEe0Bdj+kD0GNIle9s=
  file: QWeave.dmg
  on:
    repo: sunderme/QWeave
    tags: true
