language: cpp
os: osx
branches:
  only:
  - master
before_install:
- brew update
- brew install qt5
script:
- "/usr/local/opt/qt/bin/qmake QWeave.pro"
- make
- "/usr/local/opt/qt/bin/macdeployqt QWeave.app -dmg"
deploy:
  provider: bintray
  skip_cleanup: true
  file: "${TRAVIS_BUILD_DIR}/bintray.json"
  user: sunderme
  key:
    secure: M6ESgDMUIWEvFF7y4rHswZRm6lr8TD+sJi1c04FtJcYYJtdd4tRhm2YBqAOrwmNML50sfxvviDmJi2CmQVqt17/mmhTOzBHoW0bQoN6l59Xm9RYcAJj4lwEgNV0UXuQOVhFm0pyikEf1TVqFdUSmRpjqqIRNiej/kczUW6ry08YqzYNnW8hY3DwKHfmQo3pbh5w4yC5oiH9J4F1DY3VMq2UweuEYMySoSFH9BNfPTKVmf8dBWb0DVO60gZ3a6zQC+tAXfOWBNA+jXm/BifOY52oEvOX25TZkqCx8Ii526onQSMGpOVLNsxqwELdoalSr5yXrmDr5Hj2SbkVQdwJ5/fIgpMIYeh6YOIW5OPwaQjVeFm6UJNeVMi/D9OO4ll6Q9uC36O6nP9DYXhqtvFQ5BokR4Y9qAyn3TrnFBB6ITtcFfL8D/RAqdK2C89/SfFMBN9MhSCYa8eqq5ovqYQCf/B1HCIKK2MGiZHwFo3d59TcaSq3t+b2Qtdjr1kl87TRu5vn+xbfexPTPim3L50wnItZgENnhMaqmACyTK6OSeCwM1w67rK7iqyTRP9/Ld27OM7OGHNdEdhQ5dqHBLYJM2o9vfmNs5alDt6b/dWocPJl5CQW0AzV50DUt35bi+VlsIJ+TtRyrvklvT27TgJtioK3KACFNv7YNc5zj1XsAykw=
