language: cpp
os: osx
branches:
  only:
  - master
before_install:
- brew update
- brew install qt5
script:
- "/usr/local/opt/qt/bin/qmake QWeave.pro"
- make
- "/usr/local/opt/qt/bin/macdeployqt QWeave.app -dmg"
deploy:
  provider: bintray
  skip_cleanup: true
  file: "${TRAVIS_BUILD_DIR}/bintray.json"
  user: sunderme
  key:
    secure: RqyHF1D3xdNW1JdkO3eploqGDdzyrSKE+xmEPzE55Bbb9JalTFejuVDGFkK3zPnXfi7lhHUeaxi30N1FeHGlzVJXjIVgTpEMcfAklwl+UMTrLRpIOeRVkmUdigtm333hWe3sWj5CsDMtikSIn8iri8g7OnSrTIRvCGuUW9xr6g7p6aCFOlggFZoXBiP8DMfUKlus36JP7VX9pvsCV6LFtOmhWRHoSbtxGm7BB7A/gZI8DGGEYgdiiqAEl4nzX6emtvafy6X+Xf9FvRQ2jS96q98dTYITVZf4RZDtfQF1EkSQx6hKTtrJC3kuiZ2x58m3BuriSkWOQrmnTsQL3QYRwuWeDAaMWmESjITUx27xM9RH2eGgJ0JyGA48QlQDlc0Wo64W7AGHGkn2yumf/8szKACf+T5MYUnsrLDK1IhWSWcI189sePEfMa/mn8C+xS9GMwI5gb1x9p4/XdjS9yGxoSOmleevdtOzKnYb0Ba2YCsnvHW8XVOOca84Wk4GsYRPDyfmHDY+bSEIajapUOX6sGxv1iN8C7sxRTD7bNt3ykc60PP2waEBt681UcQlDDeRm6S72RZ0sDnwxYs0cZLMB7Ew8IrX/P77ExiA/bBuRTalGmUziPm3FnlAY06TJI+fple9jqRRXamoC52C0q4eEBkIJzKzLsM3LWE/Wx9+rHU=
